---
deployment:
  tasks:
    - export DEPLOYPATH=/home/user/public_html/
    - /bin/cp header.php $DEPLOYPATH
    - /bin/cp footer.php $DEPLOYPATH
    - /bin/cp index.php $DEPLOYPATH
    - /bin/cp index.json $DEPLOYPATH
    - /bin/cp -R assets $DEPLOYPATH
    - /bin/cp -R projects $DEPLOYPATH
    - /bin/cp -R tr_TR $DEPLOYPATH
