language: php
php:
  - '7.2'

services:
  - docker

before_install:
  # Update docker-engine.
  - sudo apt-get update
  - sudo apt-get install -o Dpkg::Options::="--force-confold" --force-yes -y docker-engine

  # Travis uses an older docker-composer (v1.4.2), we need to update it.
  - docker-compose --version
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/1.8.0-rc2/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - docker-compose --version

  # Do AWS login for ECR.
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin
  - eval $(aws ecr get-login --region $AWS_DEFAULT_REGION)

before_script:
  - composer self-update
  - composer install --no-interaction --prefer-source --dev
  
script: 
  - ./vendor/bin/phpunit tests

after_success:
  - cd docker
  - docker-compose -f docker-compose-prod.yml up -d --build
  - docker tag ebrukayame_web:latest $IMAGE_REPOS_BASE_URL/ebrukayame_web:latest
  - docker push $IMAGE_REPOS_BASE_URL/ebrukayame_web:latest
  - docker tag ebrukayame_php-fpm:latest $IMAGE_REPOS_BASE_URL/ebrukayame_php-fpm:latest
  - docker push $IMAGE_REPOS_BASE_URL/ebrukayame_php-fpm:latest 