version: '3'

services:
  web:
    container_name: web
    build:
      context: ./
      dockerfile: docker/nginx/Dockerfile
    ports:
      - 80:80
    volumes:
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-fpm

  php-fpm:
    container_name: php-fpm
    build:
      context: ./
      dockerfile: docker/php-fpm/Dockerfile
    volumes:
      - ./src:/srv/gits/web