version: '3'

services:
  web:
    container_name: web
    build: ./nginx
    ports:
      - 80:80
    volumes:
      - ./nginx/conf.d/default-dev.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-fpm

  php-fpm:
    container_name: php-fpm
    build: ./php-fpm
    volumes:
      - ./../src:/srv/gits/web